services:
  - type: web
    name: mediapipe-bg-landmarks
    runtime: docker
    plan: free
    envVars:
      - key: GLOG_minloglevel
        value: "3"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
